# Generated by Django 3.2.4 on 2021-06-08 15:34

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Animme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('ano_lancamento', models.DateField(default=datetime.datetime(2021, 6, 8, 15, 34, 30, 631520, tzinfo=utc))),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anime.autor')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anime.estudio')),
            ],
        ),
    ]
