# Generated by Django 3.2.4 on 2021-06-08 16:11

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animme',
            name='ano_lancamento',
            field=models.DateField(default=datetime.datetime(2021, 6, 8, 16, 11, 46, 537456, tzinfo=utc)),
        ),
    ]
