# Generated by Django 3.2.4 on 2021-06-10 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0004_auto_20210610_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anime.autor'),
        ),
        migrations.AlterField(
            model_name='anime',
            name='estudio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anime.estudio'),
        ),
    ]
