# Generated by Django 3.2.4 on 2021-06-11 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0005_auto_20210610_1228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos_manga/%Y%m%d'),
        ),
    ]
