# Generated by Django 3.2.4 on 2021-06-13 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0006_alter_anime_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='autor',
        ),
        migrations.AddField(
            model_name='anime',
            name='autor',
            field=models.ManyToManyField(to='anime.Autor'),
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.autor')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='anime.anime')),
            ],
        ),
        migrations.AddField(
            model_name='anime',
            name='artists',
            field=models.ManyToManyField(related_name='actor', through='anime.Role', to='anime.Autor'),
        ),
    ]
