# Generated by Django 3.2.4 on 2021-06-13 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0007_auto_20210613_0844'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='autor',
        ),
    ]
