# Generated by Django 3.2.4 on 2021-06-13 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0008_remove_anime_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='artists',
        ),
    ]
