# Generated by Django 3.2.4 on 2021-06-13 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0009_remove_anime_artists'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='artists',
            field=models.ManyToManyField(related_name='actor', through='anime.Role', to='anime.Autor'),
        ),
    ]
