# Generated by Django 3.2.4 on 2021-06-13 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0010_anime_artists'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='artists',
        ),
        migrations.AddField(
            model_name='anime',
            name='autor',
            field=models.ManyToManyField(to='anime.Autor'),
        ),
    ]
