# Generated by Django 3.2.4 on 2021-06-13 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0011_auto_20210613_0959'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
