# Generated by Django 3.2.4 on 2021-06-13 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0013_rename_autor_anime_autores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='autores',
            new_name='autor',
        ),
    ]
