# Generated by Django 3.2.4 on 2021-06-13 18:09

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0014_rename_autores_anime_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos_anime/%Y%m%d'),
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nome_alternativo', models.CharField(blank=True, max_length=150)),
                ('ano_lancamento', models.DateField(default=django.utils.timezone.now)),
                ('foto', models.ImageField(blank=True, upload_to='fotos_manga/%Y%m%d')),
                ('autor', models.ManyToManyField(to='anime.Autor')),
                ('estudio', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='anime.estudio')),
            ],
        ),
    ]
