# Generated by Django 3.2.4 on 2021-06-16 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0015_auto_20210613_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/fotos_anime/%Y%m%d'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='foto',
            field=models.ImageField(blank=True, upload_to='fotos/fotos_manga/%Y%m%d'),
        ),
    ]
