# Generated by Django 3.2.4 on 2021-07-06 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0016_auto_20210616_1544'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anime',
            name='autor',
        ),
        migrations.AddField(
            model_name='anime',
            name='autor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='anime.autor'),
        ),
        migrations.RemoveField(
            model_name='manga',
            name='autor',
        ),
        migrations.AddField(
            model_name='manga',
            name='autor',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.DO_NOTHING, to='anime.autor'),
        ),
    ]
