# Generated by Django 3.2.4 on 2021-07-06 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0018_auto_20210706_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='estudio',
            field=models.ManyToManyField(default='Desconhecido', to='anime.Estudio'),
        ),
    ]
