# Generated by Django 3.2.4 on 2021-07-06 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0019_alter_anime_estudio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='estudio',
            field=models.ManyToManyField(to='anime.Estudio'),
        ),
    ]
